GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJsdWlzIiwiZW1haWwiOiJsdWlzQGdtYWlsLmNvbSIsImlhdCI6MTY2OTkyNjkxOCwiZXhwIjoxNjY5OTI2OTMzfQ.1ZHXWOm3hZP_f_HyxCQxT1yAip-d44EhS9KO9IsjtHI
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"israel",
    "email": "israel@mail.com",
    "rol": "admin",
    "password": "israel",
    "confPassword": "israel"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "luis@gmail.com",
    "password":"luis"
}

###
GET http://localhost:5000/token

### 
DELETE  http://localhost:5000/logout


